/* ------------------------------------------------ */
/*                    DEPENDENCIES                  */
/* ------------------------------------------------ */
// Packages
import { Inter } from "next/font/google";

// Styles
import "./globals.scss";

/* ------------------------------------------------ */
/*                  SEO META DATA                   */
/* ------------------------------------------------ */
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* ------------------------------------------------ */
/*                     COMPONENT                    */
/* ------------------------------------------------ */
function RootLayout({ children }) {
  /* ***************** RENDERING ****************** */
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

export default RootLayout;